import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import { AuthProvider } from "@/contexts/AuthContext";
import ProtectedRoute from "@/components/ProtectedRoute";
import AppLayout from "@/components/AppLayout";
import Login from "./pages/Login";
import Dashboard from "./pages/Dashboard";
import Products from "./pages/Products";
import Sales from "./pages/Sales";
import Reports from "./pages/Reports";
import UsersPage from "./pages/UsersPage";
import SettingsPage from "./pages/SettingsPage";
import NotFound from "./pages/NotFound";
import { Toaster } from "sonner";
const queryClient = new QueryClient();
const App = () => (_jsx(QueryClientProvider, { client: queryClient, children: _jsxs(TooltipProvider, { children: [_jsx(Toaster, {}), _jsx(AuthProvider, { children: _jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/", element: _jsx(Navigate, { to: "/dashboard", replace: true }) }), _jsx(Route, { path: "/dashboard", element: _jsx(ProtectedRoute, { children: _jsx(AppLayout, { children: _jsx(Dashboard, {}) }) }) }), _jsx(Route, { path: "/products", element: _jsx(ProtectedRoute, { allowedRoles: ['SUPER_ADMIN', 'ADMIN'], children: _jsx(AppLayout, { children: _jsx(Products, {}) }) }) }), _jsx(Route, { path: "/sales", element: _jsx(ProtectedRoute, { children: _jsx(AppLayout, { children: _jsx(Sales, {}) }) }) }), _jsx(Route, { path: "/reports", element: _jsx(ProtectedRoute, { allowedRoles: ['SUPER_ADMIN', 'ADMIN'], children: _jsx(AppLayout, { children: _jsx(Reports, {}) }) }) }), _jsx(Route, { path: "/users", element: _jsx(ProtectedRoute, { allowedRoles: ['SUPER_ADMIN', 'ADMIN'], children: _jsx(AppLayout, { children: _jsx(UsersPage, {}) }) }) }), _jsx(Route, { path: "/settings", element: _jsx(ProtectedRoute, { allowedRoles: ['SUPER_ADMIN', 'ADMIN'], children: _jsx(AppLayout, { children: _jsx(SettingsPage, {}) }) }) }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] }) }) })] }) }));
export default App;
